# Database configuration
database:
    # URL where to find the database
    url: jdbc:mysql://localhost:3306/crowdcontrol?useSSL=false

    # Dialekt to use for communication
    dialect: MYSQL

    # User with read and write access
    writing:
        user: crowdcontrol
        password:

    # User with read-only access
    readonly:
        user: crowdreader
        password:

# Deployment of object-service, control-ui, worker-ui
deployment:
    # Port for the object-service (optional)
    # default value is 4567 if ommited
    port: 4567

    # Origin of the control-ui
    # Port has to match the URL of the UI and have no / at the end
    origin: http://localhost:3000

    # URL of the worker-service
    workerService: https://worker.example.com

    # URL to the root of the worker-ui with no / at the end
    # object-service will append particular file names like "/taskPresenter.html"
    workerUIPublic: https://workerui.example.com

    # Local URL of the worker-ui, for cases where the public URL cannot be accessed
    # Can be ommitted if not using Docker
    workerUILocal: http://localhost:8080

    # the secret to crypt with jwt webtokens
    jwtsecret: samplesecret
# Defined platforms to run
platforms:
    # Type to use:
    # - mturk
    # - pybossa
    # - dummy
    - type: dummy

      # Standard credentials
      user: samplePlatformUser
      password: samplePassword

      # Name which is used to display
      name: Sandbox

      # URL to the platform
      url: http://example.com/

    - type: pybossa

      # Key to access the PyBossa API
      apiKey: 8ec92fa1-1bd1-42ad-8524-3d2bab4588b1

      # URL to the PyBossa Platform
      url: http://localhost:5000

      # Name which is used to display
      name: Pybossa

      # ID of the PyBossa project to use for all experiments
      projectId: 1

      # Whether calibrations should be displayed / used on this platform
      calibrationsAllowed: true

# Basic configurations for the mail module
mail:

    #The mail address of the admin to send notifications to
    admin: pseipd@gmail.com

    # disabled = true will ignore the mail configuration and print to the command line
    disabled : true

    notifications:
        protocol: smtps
        from: max2.example.com
        auth:
            server: smtps.example.com
            port: 567
            credentials:
                user: maxMusterMannSSl
                password: SuperSecretStuff
    moneyReceiver:
        protocol: imaps
        inbox: INBOX
        auth:
            server: imap.example.com
            port: 996
            credentials:
                user: maxUserName
                password: secretpw

moneytransfer:
    # Minimum amount of money in US cent a worker has to earn before he gets paid off
    payOffThreshold: 0

    # Password used to verify a valid Amazon GiftCode e-mail
    # enter password as message on the Amazon homepage when buying GiftCodes
    parsingPassword: test

    # Interval in days, when the workers get paid off
    scheduleInterval: 7

# Map of packages to log levels, e.g.
# log:
#    org.package.name: WARN
log:
    com.zaxxer.hikari: WARN
    org.eclipse.jetty: WARN
    org.jooq.impl.DefaultBinding: WARN
    org.jooq.impl.DefaultConnectionProvider: WARN
    org.jooq.tools.StopWatch: WARN
    spark.webserver.MatcherFilter: WARN
    spark.Request: WARN