database:
    # the url where to find the database
    url: jdbc:mysql://db:3306/crowdcontrol?useSSL=false

    # dialekt to use for communication
    dialect: MYSQL

    # the writing user
    writing:
        user: root
        password: root

    # readonly user should really just be readonly
    readonly:
        user: user
        password: 123456

# basic configurations for the mail-module
mail :
    # disabled = true will ignore the mail configuration and print to the command-line
    disabled : true

# Deployment of the object service / control ui
deployment:
    # Origin of the control ui
    # port has to match the url of the ui and no / at the end
    origin: "*"
    # the local url of the worker-ui, for cases where the public url cannot be accessed (docker image)
    # can be ommitted
    workerUILocal: http://workerui:80
    jwtsecret: bGFtYWJhZGExMzY3OPxpbw==

# the defined platforms to run
platforms :
    # type to use (mturk/pybossa/dummy)
    - type: dummy
      # name which is used to display
      name: dummy
      url: http://workerui:80/

    - type: pybossa
      #apiKey: f66b69d3-467b-48ce-9822-e4e9a34403a2
      apiKey: 777d203a-e067-4fe4-aa8c-f9d88307d894
      url: http://pybossa:5000/api
      name: pybossa
      projectId: 2

moneytransfer:
    # Minimum amount of money in US cent a worker has to earn before he gets paid off
    payOffThreshold: 0

    # Password used to verify a valid Amazon GiftCode e-mail
    # enter password as message on the Amazon homepage when buying GiftCodes
    parsingPassword: test

    # E-mail address to send notification mails to
    notificationMailAddress: pseipd@gmail.com

    # Interval in days, when the workers get paid off
    scheduleInterval: 7



# Map of packages to log levels, e.g.
# log:
#    org.package.name: WARN
log:
    com.zaxxer.hikari: WARN
    org.eclipse.jetty: WARN
    org.jooq.impl.DefaultBinding: WARN
    org.jooq.impl.DefaultConnectionProvider: WARN
    org.jooq.tools.StopWatch: WARN
    spark.webserver.MatcherFilter: WARN
    spark.Request: WARN